apiVersion: v1
kind: Service
metadata:
  name: cloudnative-app
  labels:
    app: cloudnative-app
    app.kubernetes.io/name: cloudnative-app
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cloudnative-app
